### PR TITLE
use filter to replace deprecated array comprehensions, fix #85

### LINKED ISSUE #85: Doesn't work with Mozilla Firefox Nightly 46
This plugin, like others (stylish for esample, it is fixed with the last beta update), doesn't work anymore with the last version of firefox.

### PR DESCRIPTION
**Pull request by yfdyh000**

### CODE REVIEW

**Comment by yfdyh000** [comment]
Need to notice: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions requirement Firefox 22 and higher.

But we already in use it in this project. So, please consider update the minimum version to at least Firefox 22 in install.rdf and update.rdf.

**Comment by cpriest** [comment]
No problem with this change, thanks for contributing.  I am working on v3 which is a from the ground up rebuild using the WebExtensions model.

Curious what you mean by deprecated array comprehensions, are they going away?  I hadn't heard...

**Comment by cpriest** [comment]
Nevermind on the comprehensions, I saw the other other post: [old array comprehension syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions#Differences_to_the_older_JS1.7JS1.8_comprehensions)

**Comment by yfdyh000** [comment]
@cpriest Can you release it to https://addons.mozilla.org/firefox/addon/snaplinksplus/versions/, thanks.

**Comment by cpriest** [comment]
Yeah, I'll see about getting it built and uploaded tonight.

**Comment by cpriest** [comment]
So I've created a 2.4.3b4 build with the changes, I've no idea if it will work really.  Could you give it a shot and see?  https://github.com/cpriest/SnapLinksPlus/blob/master/dist/snaplinksplus-2.4.3b3.xpi?raw=true

I'm focused on a rebuild from the ground up, cross browser, etc.  I don't intend to put much of any further time into the 2.x branch.  I recall working on making this a restartless extension last, which may be where the master branch is sitting in which case it isn't complete/working.

If it works fine, let me know and I'll get it put up on addons.mozilla

**Comment by yfdyh000** [comment]
It seems to no longer works anywhere, no error messages.

**Comment by cpriest** [comment]
I think that's probably not too surprising, I'll see what I can do, I 
think I saw that I had v2.4.3 branches which probably were isolated from 
the 'restartless' aspect I had been working on.  Perhaps I can add your 
patch there and build a version from there that will work properly.  
I'll look into it as soon as I can.

**Comment by cpriest** [comment]
Okay, got things sorted out and your changes applied to the 2.4.3 branch.  I build (v2.4.3b3)[https://github.com/cpriest/SnapLinksPlus/blob/2b65b36a06d17782be9b8cf41fac8557bebd6ed9/dist/snaplinksplus-2.4.3b3.xpi?raw=true] and tested quickly in multi-process and regular FF.  Seems to work fine in regular FF.  If you concur I will get it uploaded to addons.mozilla...

**Comment by yfdyh000** [comment]
I have tested to verify that it works in Fx22-latest Nightly, not works in Fx21 and earlier. So, please change the minimum compatible version to 22.0 and the addon version, and then uploaded to AMO.
Thanks for your works.

**Comment by yfdyh000** [comment]
Also, I see that it does not works in about: pages (in about:about), it seems always been the case, perhaps it is worth to effort in the new version (v3).

**Comment by cpriest** [comment]
v2.4.3 is released/approved in addons.mozilla.org now

Thanks for the patch!

**Pull request merged**
