### PR TITLE
Fixes for #100 (1)

### PR DESCRIPTION
**Pull request by Phyxion**

### CODE REVIEW

**Comment by cpriest** [comment]
Did you try this against the current 'master' branch where the all: initial; style has been set from SnapLinks.es6?  I have not tested this issue specifically yet but I was under the impression that it should fix the issue.

**Comment by Phyxion** [comment]
Yes, I have tried that and that's not working. I'm currently using the one with my fix included and I haven't encountered a site with this issue anymore.

**Comment by cpriest** [comment]
Hmm, I'll check into it a bit more and see what's going on.  Working on 
an internal micro-service model at the moment, but want to get the next 
release out the door asap.  In the next release, i'll either include 
your patch or something else once I understand the problem better.

**Comment by Phyxion** [comment]
Alright, it's easy to verify on the website I've mentioned in #100.

**Pull request closed without merging**
