### PR TITLE
Adding possibility to disable preferences syncing

### PR DESCRIPTION
**Pull request by remi-garcia**
Fix for #313 
I cannot test it on my side and I just discovered the whole `sync` possibility for addons prefs thus I'm not sure that it will work. Need your feedback on that. Sorry.

### CODE REVIEW

**Comment by cpriest** [comment]
I'll have to check it out, I don't know why this would work unless it's relying on code for using local storage already there or is switching out a value that would make it use local prefs.  

I need to dig out the project and look at it with your code, been too long since I've seen the code.  I've had a busy year or more, sorry I've been absent; thanks for still being around!

**Comment by remi-garcia** [comment]
> I'll have to check it out, I don't know why this would work unless it's relying on code for using local storage already there or is switching out a value that would make it use local prefs.

I did some digging and I think you already had it done, the only missing part was the option. See [StoragePrefs.js](https://github.com/cpriest/SnapLinksPlus/blob/dev/src/StoragePrefs.js).

> I've had a busy year or more, sorry I've been absent; thanks for still being around!

Don't worry, it's totally understandable. You've done all the work that makes SLP3 so great, no one will complain when you have to focus on something else!

**Comment by cpriest** [comment]
Good find, I anticipated some people might not like the sync features and it was easy to code in from the start anyways.

**Comment by cpriest** [comment]
I'm a bit late in reviewing this, aren't I?  I decided to try and give this project some attention, getting things squared away and updated.

**Pull request merged**
