### PR TITLE
Adding options

### PR DESCRIPTION
**Pull request by Phyxion**
Updated according to review, this is as little as possible. 

I'm not sure why _applications_ in manifest.json is changed as I couldn't find any difference.

### CODE REVIEW

**Comment by Phyxion** [comment]
BTW, manifest.json should be "src/lib/Configs.**js**", instead of **es6**.

**Comment by cpriest** [comment]
Perhaps that's why I couldn't get it working after I merged/updated a couple of days ago.  Got up early to try and get this checked out and a beta signed/released.

**Comment by Phyxion** [comment]
Yes, I forgot to copy a few lines in the manifest file, so my bad :)

**Comment by cpriest** [comment]
Hey @Phyxion I was wondering if you still knew where this source code came from?  I can't find it anywhere on the 'net.  Was looking to see if it had been updated or if I could fork it or atleast attribute it correctly.

**Comment by cpriest** [comment]
Or did you write this yourself?

**Comment by Phyxion** [comment]
No, I didn't  :)
It's actually in the file itself (as license), https://github.com/piroor/webextensions-lib-configs

**Comment by cpriest** [comment]
Whoops, my IDE must be setup to put in my copyright notice, kindof old school.  Glad I went looking for the source as that isn't right.  Thanks!

**Pull request merged**
